[package]
name = "gpt2_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpt2_proto = { path = "../proto" }
tonic = "0.6.2"
